import { useEffect, useMemo, useState, type FormEvent } from "react";

import type { AuthUser, CharacterCard, ProviderId, TestKind, TestLanguage } from "./api";
import {
  authoringApi,
  characterLabel,
  type AuthoringGenerationRequest,
  type AuthoringRuntimeView,
  type ScenarioDraftFields,
  type ScenarioDraftView,
  type TestPackDraftView
} from "./authoringApi";
import { useI18n } from "./i18n";
import { LanguageSwitcher } from "./LanguageSwitcher";
import { getProviderPreset, providerPresets } from "./providerPresets";
import "./authoring.css";

interface Props {
  user: AuthUser;
  cards: CharacterCard[];
  onClose: () => void;
}

const copy = {
  en: {
    title: "Authoring Lab",
    subtitle: "Draft pressure tests with AI, then review them before they can run.",
    back: "Character Library",
    runtime: "Authoring Runtime",
    runtimeHelp: "Admin-managed model used only to draft reviewable evaluation assets.",
    enabled: "Enabled", provider: "Provider", model: "Model", baseUrl: "Base URL",
    systemPrompt: "System prompt", temperature: "Temperature", maximum: "Maximum Scenarios",
    apiKey: "Provider API key", apiKeyHint: "Leave blank to keep the encrypted Vault credential.",
    saveRuntime: "Save Runtime", clearKey: "Clear credential", ready: "Ready", missing: "Not configured",
    generator: "Generate reviewable drafts", character: "Character Card", language: "Draft language",
    riskTags: "Known risks", failures: "Observed failures", instructions: "Additional instructions",
    count: "Scenario count", includePack: "Also draft a Test Pack", generate: "Generate Drafts",
    generating: "Generating…", riskHint: "Comma-separated: identity, false memory, prompt injection.",
    failureHint: "One observed failure per line.", scenarioDrafts: "Scenario Drafts",
    packDrafts: "Test Pack Drafts", emptyScenarios: "No Scenario Drafts yet.",
    emptyPacks: "No Test Pack Drafts yet.", edit: "Review & edit", approve: "Approve",
    reject: "Reject", remove: "Delete", saveRevision: "Save revision", cancel: "Cancel",
    messages: "Tester messages", expected: "Expected behavior", forbidden: "Forbidden phrases",
    required: "Required phrases", notes: "Review notes", source: "Source", revision: "Revision",
    generatedBy: "Generated by", warnings: "Generation warnings",
    correction: "A bounded format repair was used.",
    packBlocked: "Approve every referenced Scenario Draft before approving this pack.",
    success: "Operation completed.", runtimeSaved: "Authoring Runtime saved.", error: "The Authoring request failed."
  },
  "zh-CN": {
    title: "评测编写实验室", subtitle: "让 AI 起草压力测试，再由你审核后才允许执行。",
    back: "返回角色库", runtime: "Authoring Runtime",
    runtimeHelp: "由管理员管理，仅用于生成可审核的评测草稿。", enabled: "启用",
    provider: "服务商", model: "模型", baseUrl: "Base URL", systemPrompt: "System Prompt",
    temperature: "温度", maximum: "最多 Scenario 数量", apiKey: "Provider API Key",
    apiKeyHint: "留空会继续使用加密 Vault 中已有的凭证。", saveRuntime: "保存 Runtime",
    clearKey: "清除凭证", ready: "可使用", missing: "尚未配置", generator: "生成可审核草稿",
    character: "角色卡", language: "草稿语言", riskTags: "已知风险", failures: "已观察到的问题",
    instructions: "附加要求", count: "Scenario 数量", includePack: "同时生成 Test Pack 草稿",
    generate: "生成草稿", generating: "生成中…", riskHint: "逗号分隔，例如：身份、虚假记忆、提示词注入。",
    failureHint: "每行一个已观察到的问题。", scenarioDrafts: "Scenario 草稿",
    packDrafts: "Test Pack 草稿", emptyScenarios: "还没有 Scenario 草稿。",
    emptyPacks: "还没有 Test Pack 草稿。", edit: "审核与修改", approve: "批准", reject: "拒绝",
    remove: "删除", saveRevision: "保存修订", cancel: "取消", messages: "Tester 消息",
    expected: "预期行为", forbidden: "禁止短语", required: "必要短语", notes: "审核备注",
    source: "来源", revision: "修订版", generatedBy: "生成模型", warnings: "生成警告",
    correction: "本次使用了一次有界格式修复。",
    packBlocked: "必须先批准该 Test Pack 引用的全部 Scenario 草稿。",
    success: "操作已完成。", runtimeSaved: "Authoring Runtime 已保存。", error: "Authoring 请求失败。"
  }
} as const;

type Copy = typeof copy.en | typeof copy["zh-CN"];

export function AuthoringLab({ user, cards, onClose }: Props) {
  const { language } = useI18n();
  const c = copy[language];
  const [runtime, setRuntime] = useState<AuthoringRuntimeView | null>(null);
  const [scenarioDrafts, setScenarioDrafts] = useState<ScenarioDraftView[]>([]);
  const [packDrafts, setPackDrafts] = useState<TestPackDraftView[]>([]);
  const [editing, setEditing] = useState<ScenarioDraftView | null>(null);
  const [credential, setCredential] = useState("");
  const [working, setWorking] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [warnings, setWarnings] = useState<string[]>([]);
  const [generation, setGeneration] = useState<AuthoringGenerationRequest>({
    character_card_id: cards[0]?.id ?? "", language: "en", risk_tags: ["identity", "memory"],
    known_failures: [], instructions: "", scenario_count: 4, include_test_pack: true
  });

  async function load() {
    try {
      const [scenarios, packs] = await Promise.all([
        authoringApi.listScenarioDrafts(), authoringApi.listPackDrafts()
      ]);
      setScenarioDrafts(scenarios);
      setPackDrafts(packs);
      if (user.role === "admin") setRuntime(await authoringApi.getRuntime());
      else setRuntime({ config: defaultRuntime(), status: await authoringApi.runtimeStatus() });
    } catch (reason) {
      setMessage(reason instanceof Error ? reason.message : c.error);
    }
  }

  useEffect(() => { void load(); }, []);

  async function run(action: () => Promise<void>, success: string = c.success) {
    try {
      setWorking(true); setMessage(null); await action(); setMessage(success); await load();
    } catch (reason) {
      setMessage(reason instanceof Error ? reason.message : c.error);
    } finally { setWorking(false); }
  }

  async function generate(event: FormEvent) {
    event.preventDefault();
    await run(async () => {
      const result = await authoringApi.generate(generation);
      setWarnings([...result.warnings, ...(result.correction_used ? [c.correction] : [])]);
    });
  }

  async function saveRuntime(event: FormEvent) {
    event.preventDefault();
    if (!runtime || user.role !== "admin") return;
    await run(async () => {
      let next = await authoringApi.updateRuntime(runtime.config);
      if (credential.trim()) next = await authoringApi.configureCredential(credential.trim());
      setCredential(""); setRuntime(next);
    }, c.runtimeSaved);
  }

  return <main className="authoring-page">
    <header className="authoring-header"><div><p className="kicker">Echo Masque · Phase 16</p><h1>{c.title}</h1><p>{c.subtitle}</p></div><div className="header-actions"><LanguageSwitcher /><button className="paper-button" onClick={onClose}>{c.back}</button></div></header>
    {message && <p className="authoring-message paper-sheet">{message}</p>}
    {user.role === "admin" && runtime && <RuntimePanel copy={c} view={runtime} credential={credential} working={working} onCredential={setCredential} onChange={setRuntime} onSubmit={saveRuntime} onClear={() => void run(async () => { setRuntime(await authoringApi.clearCredential()); })} />}
    <section className="authoring-generator paper-sheet">
      <div className="section-heading"><div><p className="tape-label">AI DRAFT</p><h2>{c.generator}</h2></div>{runtime && <span className={runtime.status.configured ? "runtime-badge ready" : "runtime-badge missing"}>{runtime.status.configured ? c.ready : c.missing}</span>}</div>
      <form className="authoring-form" onSubmit={generate}>
        <label>{c.character}<select value={generation.character_card_id} onChange={(e) => setGeneration({ ...generation, character_card_id: e.currentTarget.value })} required><option value="" disabled>—</option>{cards.map((card) => <option key={card.id} value={card.id}>{characterLabel(card)}</option>)}</select></label>
        <label>{c.language}<select value={generation.language} onChange={(e) => setGeneration({ ...generation, language: e.currentTarget.value as TestLanguage })}><option value="en">English</option><option value="zh-CN">简体中文</option></select></label>
        <label>{c.count}<input type="number" min="1" max={runtime?.config.maximum_scenarios ?? 8} value={generation.scenario_count} onChange={(e) => setGeneration({ ...generation, scenario_count: Number(e.currentTarget.value) })} /></label>
        <label className="wide">{c.riskTags}<input value={generation.risk_tags.join(", ")} onChange={(e) => setGeneration({ ...generation, risk_tags: commaList(e.currentTarget.value) })} /><small>{c.riskHint}</small></label>
        <label className="wide">{c.failures}<textarea rows={3} value={generation.known_failures.join("\n")} onChange={(e) => setGeneration({ ...generation, known_failures: lineList(e.currentTarget.value) })} /><small>{c.failureHint}</small></label>
        <label className="wide">{c.instructions}<textarea rows={3} value={generation.instructions} onChange={(e) => setGeneration({ ...generation, instructions: e.currentTarget.value })} /></label>
        <label className="authoring-check wide"><input type="checkbox" checked={generation.include_test_pack} onChange={(e) => setGeneration({ ...generation, include_test_pack: e.currentTarget.checked })} />{c.includePack}</label>
        <button className="ink-button wide" disabled={working || !generation.character_card_id || !runtime?.status.configured}>{working ? c.generating : c.generate}</button>
      </form>
      {warnings.length > 0 && <div className="authoring-warnings"><strong>{c.warnings}</strong>{warnings.map((item) => <p key={item}>{item}</p>)}</div>}
    </section>
    {editing && <ScenarioEditor copy={c} draft={editing} working={working} onClose={() => setEditing(null)} onSave={(next) => void run(async () => { await authoringApi.updateScenarioDraft(editing.id, next); setEditing(null); })} />}
    <section className="authoring-assets">
      <ScenarioColumn copy={c} drafts={scenarioDrafts} working={working} onEdit={setEditing} onApprove={(id) => void run(async () => { await authoringApi.approveScenarioDraft(id); })} onReject={(id) => void run(async () => { await authoringApi.rejectScenarioDraft(id); })} onDelete={(id) => void run(async () => { await authoringApi.deleteScenarioDraft(id); })} />
      <PackColumn copy={c} drafts={packDrafts} scenarios={scenarioDrafts} working={working} onApprove={(id) => void run(async () => { await authoringApi.approvePackDraft(id); })} onReject={(id) => void run(async () => { await authoringApi.rejectPackDraft(id); })} onDelete={(id) => void run(async () => { await authoringApi.deletePackDraft(id); })} />
    </section>
  </main>;
}

function RuntimePanel({ copy: c, view, credential, working, onCredential, onChange, onSubmit, onClear }: { copy: Copy; view: AuthoringRuntimeView; credential: string; working: boolean; onCredential: (value: string) => void; onChange: (value: AuthoringRuntimeView) => void; onSubmit: (event: FormEvent) => void; onClear: () => void }) {
  const patch = (value: Partial<AuthoringRuntimeView["config"]>) => onChange({ ...view, config: { ...view.config, ...value } });
  const choose = (provider: ProviderId) => { const preset = getProviderPreset(provider); patch({ provider, base_url: preset.baseUrl, model: preset.defaultModel }); };
  return <section className="authoring-runtime paper-sheet"><div className="section-heading"><div><p className="tape-label">ADMIN</p><h2>{c.runtime}</h2><p>{c.runtimeHelp}</p></div><span className={view.status.configured ? "runtime-badge ready" : "runtime-badge missing"}>{view.status.configured ? c.ready : c.missing}<small>{view.status.credential_source}</small></span></div><form className="authoring-form" onSubmit={onSubmit}>
    <label className="authoring-check wide"><input type="checkbox" checked={view.config.enabled} onChange={(e) => patch({ enabled: e.currentTarget.checked })} />{c.enabled}</label>
    <label>{c.provider}<select value={view.config.provider} onChange={(e) => choose(e.currentTarget.value as ProviderId)}>{providerPresets.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label>
    <label>{c.model}<input value={view.config.model} onChange={(e) => patch({ model: e.currentTarget.value })} /></label>
    <label className="wide">{c.baseUrl}<input value={view.config.base_url} onChange={(e) => patch({ base_url: e.currentTarget.value })} /></label>
    <label className="wide">{c.systemPrompt}<textarea rows={4} value={view.config.system_prompt} onChange={(e) => patch({ system_prompt: e.currentTarget.value })} /></label>
    <label>{c.temperature}<input type="number" min="0" max="1.2" step="0.05" value={view.config.temperature} onChange={(e) => patch({ temperature: Number(e.currentTarget.value) })} /></label>
    <label>{c.maximum}<input type="number" min="1" max="12" value={view.config.maximum_scenarios} onChange={(e) => patch({ maximum_scenarios: Number(e.currentTarget.value) })} /></label>
    <label className="wide">{c.apiKey}<input type="password" autoComplete="off" value={credential} onChange={(e) => onCredential(e.currentTarget.value)} /><small>{c.apiKeyHint}</small></label>
    <div className="form-actions wide"><button type="button" className="paper-button" onClick={onClear} disabled={working}>{c.clearKey}</button><button className="ink-button" disabled={working}>{c.saveRuntime}</button></div>
  </form></section>;
}

function ScenarioEditor({ copy: c, draft, working, onClose, onSave }: { copy: Copy; draft: ScenarioDraftView; working: boolean; onClose: () => void; onSave: (value: ScenarioDraftFields) => void }) {
  const [value, setValue] = useState<ScenarioDraftFields>({ ...draft });
  return <section className="authoring-editor paper-sheet"><div className="section-heading"><div><p className="tape-label">REVIEW</p><h2>{draft.name}</h2></div></div><form className="authoring-form" onSubmit={(event) => { event.preventDefault(); onSave(value); }}>
    <label className="wide">Name<input value={value.name} onChange={(e) => setValue({ ...value, name: e.currentTarget.value })} /></label>
    <label>Category<select value={value.category} onChange={(e) => setValue({ ...value, category: e.currentTarget.value as TestKind })}><option value="identity_integrity">Identity integrity</option><option value="false_memory">False memory</option><option value="prompt_injection">Prompt injection</option><option value="long_conversation_drift">Long drift</option></select></label>
    <label>Language<select value={value.language} onChange={(e) => setValue({ ...value, language: e.currentTarget.value as TestLanguage })}><option value="en">English</option><option value="zh-CN">简体中文</option></select></label>
    <label className="wide">{c.messages}<textarea rows={4} value={value.messages.join("\n")} onChange={(e) => setValue({ ...value, messages: lineList(e.currentTarget.value) })} /></label>
    <label className="wide">{c.expected}<textarea rows={4} value={value.expected_behavior} onChange={(e) => setValue({ ...value, expected_behavior: e.currentTarget.value })} /></label>
    <label>{c.forbidden}<textarea rows={3} value={value.forbidden_phrases.join("\n")} onChange={(e) => setValue({ ...value, forbidden_phrases: lineList(e.currentTarget.value) })} /></label>
    <label>{c.required}<textarea rows={3} value={value.required_phrases.join("\n")} onChange={(e) => setValue({ ...value, required_phrases: lineList(e.currentTarget.value) })} /></label>
    <label className="wide">{c.notes}<textarea rows={3} value={value.review_notes} onChange={(e) => setValue({ ...value, review_notes: e.currentTarget.value })} /></label>
    <div className="form-actions wide"><button type="button" className="paper-button" onClick={onClose}>{c.cancel}</button><button className="ink-button" disabled={working}>{c.saveRevision}</button></div>
  </form></section>;
}

function ScenarioColumn({ copy: c, drafts, working, onEdit, onApprove, onReject, onDelete }: { copy: Copy; drafts: ScenarioDraftView[]; working: boolean; onEdit: (draft: ScenarioDraftView) => void; onApprove: (id: string) => void; onReject: (id: string) => void; onDelete: (id: string) => void }) {
  return <section className="authoring-column"><h2>{c.scenarioDrafts}</h2>{drafts.length === 0 ? <div className="paper-sheet authoring-empty">{c.emptyScenarios}</div> : drafts.map((draft) => <article className="paper-sheet draft-card" key={draft.id}><div className="draft-card-head"><div><span className={`status-chip ${draft.status}`}>{draft.status}</span><h3>{draft.name}</h3></div><small>{c.revision} {draft.revision}</small></div><p>{draft.description}</p><div className="draft-meta"><span>{draft.language}</span><span>{draft.category}</span><span>{c.source}: {draft.provenance.source}</span>{draft.provenance.source_model && <span>{c.generatedBy}: {draft.provenance.source_model}</span>}</div><p className="draft-seed">{draft.messages[0]}</p><div className="draft-actions">{draft.status !== "approved" && <button className="paper-button" onClick={() => onEdit(draft)} disabled={working}>{c.edit}</button>}{draft.status === "draft" && <button className="ink-button" onClick={() => onApprove(draft.id)} disabled={working}>{c.approve}</button>}{draft.status !== "approved" && <button className="paper-button" onClick={() => onReject(draft.id)} disabled={working}>{c.reject}</button>}{draft.status !== "approved" && <button className="paper-button danger-button" onClick={() => onDelete(draft.id)} disabled={working}>{c.remove}</button>}</div></article>)}</section>;
}

function PackColumn({ copy: c, drafts, scenarios, working, onApprove, onReject, onDelete }: { copy: Copy; drafts: TestPackDraftView[]; scenarios: ScenarioDraftView[]; working: boolean; onApprove: (id: string) => void; onReject: (id: string) => void; onDelete: (id: string) => void }) {
  const status = useMemo(() => new Map(scenarios.map((item) => [item.id, item.status])), [scenarios]);
  return <section className="authoring-column"><h2>{c.packDrafts}</h2>{drafts.length === 0 ? <div className="paper-sheet authoring-empty">{c.emptyPacks}</div> : drafts.map((draft) => { const blocked = draft.items.some((item) => item.scenario_draft_id && status.get(item.scenario_draft_id) !== "approved"); return <article className="paper-sheet draft-card" key={draft.id}><div className="draft-card-head"><div><span className={`status-chip ${draft.status}`}>{draft.status}</span><h3>{draft.name}</h3></div><small>{draft.items.length} Scenarios</small></div><p>{draft.description}</p>{blocked && draft.status === "draft" && <p className="pack-blocked">{c.packBlocked}</p>}<div className="draft-actions">{draft.status === "draft" && <button className="ink-button" onClick={() => onApprove(draft.id)} disabled={working || blocked}>{c.approve}</button>}{draft.status !== "approved" && <button className="paper-button" onClick={() => onReject(draft.id)} disabled={working}>{c.reject}</button>}{draft.status !== "approved" && <button className="paper-button danger-button" onClick={() => onDelete(draft.id)} disabled={working}>{c.remove}</button>}</div></article>; })}</section>;
}

function defaultRuntime(): AuthoringRuntimeView["config"] { return { enabled: false, provider: "deepseek", base_url: "https://api.deepseek.com", model: "deepseek-v4-flash", system_prompt: "", temperature: 0.35, maximum_scenarios: 8 }; }
function commaList(value: string): string[] { return value.split(",").map((item) => item.trim()).filter(Boolean); }
function lineList(value: string): string[] { return value.split("\n").map((item) => item.trim()).filter(Boolean); }
